#!/usr/bin/env bash
export EDITOR="nano"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export PATH="${HOME}/.local/bin:${HOME}/bin:${PATH}"
export CR_PAT="op://Private/GHCR_PAT/CR_PAT"
export SSH_AUTH_SOCK=~/.1password/agent.sock
