#!/usr/bin/env bash
#this file has things for both .zshrc and .bashrc

#uncomment to log all terminal sessions to log file
#mkdir -p ${HOME}/.shell_logs && grep -qx "$PPID" <(pgrep -x "script") || (scr>

#source functions
if [ -f ~/.shell_functions ]
then
    . ~/.shell_functions
fi

#source variables
if [ -f ~/.shell_vars ]
then
    . ~/.shell_vars
fi

#source aliases
if [ -f ~/.shell_aliases ]
then
    . ~/.shell_aliases
fi
