#!/usr/bin/env bash
alias tm='tmux attach || tmux'
alias conda-init='. ${HOME}/.local/lib/miniconda3/etc/profile.d/conda.sh'
alias bw-unlock='export BW_SESSION=$(bw unlock --raw)'
alias bw-login='export BW_SESSION=$(bw login --raw)'
