#!/usr/bin/env bash
alias tm='tmux attach || tmux'
alias conda-init='. ${HOME}/.local/lib/miniconda3/etc/profile.d/conda.sh'
alias opsignin='eval $(op signin)'
alias cdc='cd ${HOME}/.local/share/chezmoi'
if command -v exa >/dev/null 2>&1
then
  alias ll='exa -lhg'
else
  alias ll='ls -lh'
fi
