add_newline = true
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$username\
$hostname\
$time\
$line_break\
$conda\
$python\
$rlang\
$character"""

[username]
show_always = true
style_root = "bold red"
style_user = "dimmed yellow"
format = " [$user]($style)"

[hostname]
ssh_only = true
format = "@[$hostname$ssh_symbol]($style)"
trim_at = ""

[directory]
style = "blue"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncation_symbol = ".. "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[fill]
symbol = " "
style = "bold black"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
show_milliseconds = false

[time]
disabled = false
format = " \\[[$time]($style)\\]"
style = "dimmed white"

[conda]
ignore_base = false
format = "[$symbol\\($environment\\)]($style) "

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[rlang]
format = "via [R ($version )]($style)"
detect_files = ['.Rprofile', 'DESCRIPTION']

[singularity]
